export const typeOptions = [
  { label: 'Bodies', value: 'bodies' },
  { label: 'Wheels', value: 'wheels' },
  { label: 'Boosts', value: 'boosts' },
  { label: 'Antennas', value: 'antennas' },
  { label: 'Decals', value: 'decals' },
  { label: 'Toppers', value: 'toppers' },
  { label: 'Trails', value: 'trails' },
  { label: 'Goal Explosions', value: 'goal_explosions' },
  { label: 'Paints', value: 'paints' },
  { label: 'Banners', value: 'banners' },
  { label: 'Engine Audio', value: 'engine_audio' },
  { label: 'Avatar Borders', value: 'avatar_borders' },
  { label: 'Titles', value: 'titles' },
  { label: 'Crates', value: 'crates' },
];

export const rarityOptions = [
  { label: 'Common', value: 'common' },
  { label: 'Uncommon', value: 'uncommon' },
  { label: 'Rare', value: 'rare' },
  { label: 'Very Rate', value: 'very_rare' },
  { label: 'Import', value: 'import' },
  { label: 'Exotic', value: 'exotic' },
  { label: 'Black Market', value: 'black_market' },
];

export const colourOptions = [
  { label: 'Default', value: '' },
  { label: 'Burnt Sienna', value: 'burnt_sienna' },
  { label: 'Lime', value: 'lime' },
  { label: 'Titanium White', value: 'titanium_white' },
  { label: 'Cobalt', value: 'cobalt' },
  { label: 'Crimson', value: 'crimson' },
  { label: 'Forest Green', value: 'forest_green' },
  { label: 'Grey', value: 'grey' },
  { label: 'Orange', value: 'orange' },
  { label: 'Pink', value: 'pink' },
  { label: 'Purple', value: 'purple' },
  { label: 'Saffron', value: 'saffron' },
  { label: 'Sky Blue', value: 'sky_blue' },
  { label: 'Black', value: 'black' },
];

export const certificationOptions = [
  { label: 'None', value: '' },
  { label: 'Acrobat', value: 'acrobat' },
  { label: 'Aviator', value: 'aviator' },
  { label: 'Goalkeeper', value: 'goalkeeper' },
  { label: 'Guardian', value: 'guardian' },
  { label: 'Juggler', value: 'juggler' },
  { label: 'Paragon', value: 'paragon' },
  { label: 'Playmaker', value: 'playmaker' },
  { label: 'Scorer', value: 'scorer' },
  { label: 'Show-Off', value: 'show_off' },
  { label: 'Sniper', value: 'sniper' },
  { label: 'Striker', value: 'striker' },
  { label: 'Sweeper', value: 'sweeper' },
  { label: 'Tactician', value: 'tactician' },
  { label: 'Turtle', value: 'turtle' },
  { label: 'Victor', value: 'victor' },
];
